server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

spring:
  cloud:
    config:
      enabled: false
