server:
  port: 8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
      serviceUrl:
        defaultZone: http://localhost:9000/eureka/
      healthcheck:
            enabled: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

spring:
  profiles: heroku
  rabbitmq:

server:
  port: ${PORT}

eureka:
  instance:
    hostname: ${HEROKU_APP_NAME}
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.hostname}.herokuapp.com/admin/info
    healthCheckUrl: https://${eureka.hostname}.herokuapp.com/admin/health
    homePageUrl: https://${eureka.hostname}.herokuapp.com/

  client:
    serviceUrl:
      defaultZone: https://${EUREKA_APP_NAME}.herokuapp.com/eureka/

