server:
  port: 8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
      serviceUrl:
        defaultZone: http://localhost:9000/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
