server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
