server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
          enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

spring:
  profiles: heroku
  rabbitmq:

server:
  port: ${PORT}

eureka:
  instance:
    hostname: ${HEROKU_APP_NAME}.herokuapp.com
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.hostname}/admin/info
    healthCheckUrl: https://${eureka.hostname}/admin/health
    homePageUrl: https://${eureka.hostname}/

  client:
    serviceUrl:
      defaultZone: https://${EUREKA_APP_NAME}.herokuapp.com/eureka/