server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
          enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

spring:
  profiles: cloud

memcache-url: